import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Navbar from '../components/Navbar';
import Head from 'next/head';

function MyApp({ Component, pageProps }: AppProps) {
  console.log("%cIf you like what you see, I'd love to work with you!", 'background: linear-gradient(153deg,#8fdceb,#142e64); padding: 2em; font-size: 2em; font-weight: bold; color: white');
  console.log("%cEmail me >>> jshetler7@gmail.com", 'background: linear-gradient(153deg,#8fdceb,#142e64); padding: 1em; font-size: 2em; font-weight: bold; color: white');

  return <>
        <Head>
        <title>Jared Shetler Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon-16x16.png" />
        <link rel="manifest" href="/assets/site.webmanifest" />
      </Head>
    <div className='bg-slate-100 dark:bg-gray-900'>
      <Navbar />
      <Component {...pageProps} />
    </div>
  </>

}

export default MyApp
